### ISSUE TITLE
Ucięta nazwa wątków w Ostatnia aktywność

### ISSUE THREAD

**Issue by olekstomek** [adam-boduch/coyote#461]
Problem dotyczy nazw wątków w sekcji "Ostatnia aktywność" w wersji mobilnej jak i dekstopowej. 
![4p-dekstop](https://user-images.githubusercontent.com/26818304/61615321-027e8b00-ac66-11e9-9565-77dbe23daac4.PNG)
![4p-mobile](https://user-images.githubusercontent.com/26818304/61615322-03172180-ac66-11e9-9c7d-edf1ec96a2e2.PNG)
Dobrym rozwiązaniem wydaje się żeby nazwy wątków wyglądały tak jak są prezentowane np wątki w "Najwyżej oceniane", czyli zbyt długa nazwa wątku jest przycięta i kończy się "..." a także po najechaniu myszą na nazwę wątku pokazuje się tooltip z pełną nazwą wątku.

**Comment by adam-boduch** [comment]
Hmmm, niby uzyty jest taki styl, ale nie dziala

```css
#box-forum .media-body p {
    margin: 0;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```

Jakies sugestie?
